apiVersion: v1
kind: Secret
metadata:
  name: {{ .Metadata.Name }}
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: {{ .Data.TLSCert }}
  tls.key: {{ .Data.TLSKey }}